name: Restart Tao Support Bot

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.ORACLE_CLOUD_PRIVATE_KEY }}
          HOST: ${{ secrets.ORACLE_CLOUD_HOST }}
          USERNAME: ${{ secrets.ORACLE_CLOUD_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOST << 'EOF'
            cd /home/ubuntu/bot
            git pull
            npm run update-package
            npm ci
            npm run build
            sudo systemctl restart bot
          EOF
          rm -f private_key